name: savageapi
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^5.0.0
  pedantic: ^1.10.0
  test: ^1.17.11
dependencies:
  dartz: ^0.10.0
  equatable: ^2.0.3
  json_annotation: ^4.1.0
  postgrest: ^0.1.5
  supabase: ^0.2.3
